trigger:
  - master
  - dev
  - release

resources:
  - repo: self

variables:
  - template: pipeline/variables/vars.yaml
  - template: pipeline/variables/conf.yml

stages:
    
  - stage: Build
    displayName: Docker Image
    jobs:
      - template: /pipeline/templates/branch-build-push-jobs.yml
  - stage: Deploy
    displayName: Deploy To Kubernetes
    dependsOn: Build
    jobs:
      - template: /pipeline/templates/deploy-image-to-k8s-jobs.yml
      
      
  - stage: BuildWinService
    displayName: Docker Image (Win Service)
    jobs:
      - template: /pipeline/templates/branch-build-push-jobs-2.yml
  - stage: DeployWinService
    displayName: Deploy To Kubernetes (Win Service)
    dependsOn: BuildWinService
    jobs:
      - template: /pipeline/templates/deploy-image-to-k8s-jobs-2.yml
      
      
  - stage: BuildSyncWinService
    displayName: Docker Image (Sync Win Service)
    jobs:
      - template: /pipeline/templates/branch-build-push-jobs-3.yml
  - stage: DeploySyncWinService
    displayName: Deploy To Kubernetes (Sync Win Service)
    dependsOn: BuildSyncWinService
    jobs:
      - template: /pipeline/templates/deploy-image-to-k8s-jobs-3.yml
      
