name: Run Tests

on: workflow_call
jobs:
  build:
    name: Test Execution
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  

    - name: Set Environment Variables
      uses: ./.github/actions/setvars
      with:
        varFilePath: ./.github/variables/vars.env

    - name: Initialize dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          2.1.x
          3.1.x
          6.0.x        

    - name: Install coverlet.console
      run: dotnet tool install --global coverlet.console

    - name: Run Tests on WebService
      working-directory: ./src
      shell: pwsh
      run: |
        dotnet restore "./${{ env.SOLUTION_NAME }}" -s https://api.nuget.org/v3/index.json -s https://nuget.selise.biz/nuget
        dotnet build "./${{ env.SOLUTION_NAME }}" --no-incremental

        dotnet test ./XUnitTests/XUnitTests.csproj /p:CollectCoverage=true --no-build --collect:"XPlat Code Coverage"
        dotnet test "./XUnitTests/XUnitTests.csproj" --no-build --verbosity normal --logger:"junit;LogFilePath=test-results/xunit_results-WebService.xml"

    - name: Run Tests on WinService
      working-directory: ./src
      shell: pwsh
      run: |
        dotnet restore "./${{ env.SOLUTION_NAME_WIN }}" -s https://api.nuget.org/v3/index.json -s https://nuget.selise.biz/nuget
        dotnet build "./${{ env.SOLUTION_NAME_WIN }}" --no-incremental

        dotnet test ./XUnitTests/XUnitTests.csproj /p:CollectCoverage=true --no-build --collect:"XPlat Code Coverage"
        dotnet test "./XUnitTests/XUnitTests.csproj" --no-build --verbosity normal --logger:"junit;LogFilePath=test-results/xunit_results-WinService.xml"
        

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2.9.0
      if: always()
      with:
        files: "**/*.trx"
