name: Build (stg)

on:
  push:
    branches:
      - stg
  pull_request:
    branches:
      - stg
    types:
      - opened

env:
  RUN_UNIT_TEST: "false"
  RUN_SONARQUBE: "false"
  
jobs:
  initialization:
    runs-on: ubuntu-22.04
    outputs:
      envvalue1: ${{ steps.setvar.outputs.envvar1 }}
      envvalue2: ${{ steps.setvar.outputs.envvar2 }}
    steps:
      - name: set value
        id: setvar
        run: |
          echo envvar1="$RUN_UNIT_TEST" >> $GITHUB_OUTPUT
          echo envvar2="$RUN_SONARQUBE" >> $GITHUB_OUTPUT 
          
  test-job:
    if: ${{ needs.initialization.outputs.envvalue1=='true' }}
    uses: ./.github/workflows/1_test.yml
    needs: [initialization]

  sonarqube-job:
    if: ${{ success() && needs.initialization.outputs.envvalue2=='true' }}
    uses: ./.github/workflows/2_sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_GLOBAL }}
    needs: [test-job]

  cd-job:
    if: ${{ github.event_name == 'push' && (success() || (needs.initialization.outputs.envvalue1=='false' && needs.initialization.outputs.envvalue2=='false')) }}
    uses: ./.github/workflows/3_web.yml
    with:
      CONTAINER_NAME: "stg-$SERVICE_NAME"
      NAMESPACE: "stg-$SERVICE_NAME"
      SERVICE_NAME: $SERVICE_NAME
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      ClUSTER_RESOURCE_GROUP: ${{ secrets.ClUSTER_RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.STG_CLUSTER }}
      ACR_RESOURCE_GROUP: ${{ secrets.ACR_RESOURCE_GROUP }}
    needs: [sonarqube-job]

  cd-job-win:
    if: ${{ github.event_name == 'push' && (success() || (needs.initialization.outputs.envvalue1=='false' && needs.initialization.outputs.envvalue2=='false')) }}
    uses: ./.github/workflows/4_win.yml
    with:
      CONTAINER_NAME: "stg-$SERVICE_NAME-win"
      NAMESPACE: "stg-$SERVICE_NAME"
      SERVICE_NAME: $SERVICE_NAME
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      ClUSTER_RESOURCE_GROUP: ${{ secrets.ClUSTER_RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.STG_CLUSTER }}
      ACR_RESOURCE_GROUP: ${{ secrets.ACR_RESOURCE_GROUP }}    
    needs: [sonarqube-job]

  cd-job-winsync:
    if: ${{ github.event_name == 'push' && (success() || (needs.initialization.outputs.envvalue1=='false' && needs.initialization.outputs.envvalue2=='false')) }}
    uses: ./.github/workflows/5_winsync.yml
    with:
      CONTAINER_NAME: "stg-$SERVICE_NAME-winsync"
      NAMESPACE: "stg-$SERVICE_NAME"
      SERVICE_NAME: $SERVICE_NAME
    secrets:
      SELISE_GITHUB_PAT: ${{ secrets.SELISE_GITHUB_PAT }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      ClUSTER_RESOURCE_GROUP: ${{ secrets.ClUSTER_RESOURCE_GROUP }}
      CLUSTER_NAME: ${{ secrets.STG_CLUSTER }}
      ACR_RESOURCE_GROUP: ${{ secrets.ACR_RESOURCE_GROUP }}    
    needs: [sonarqube-job]    
